[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --strict-markers"
testpaths = [
    "tests",
]
markers = [
    "e2e: End-to-end integration tests",
    "tier0: Demo-blocking basic functionality tests",
    "tier1: Functional feature tests", 
    "tier2: Governance and compliance tests",
    "tier3: Resilience and scale tests",
    "slow: Tests that take more than 10 seconds",
    "integration: Integration tests requiring external services",
    "unit: Unit tests for isolated components"
]
